# Generated by Django 2.2.10 on 2020-02-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='count',
            new_name='counts',
        ),
    ]
