# Generated by Django 2.2.10 on 2020-02-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200221_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='topwords',
            field=models.TextField(default='000000'),
        ),
    ]
