# Generated by Django 2.2.10 on 2020-02-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_fulltext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='fulltext',
        ),
    ]
